### PR TITLE
Deploy parser contract hash

### PR DESCRIPTION
**Pull request by DevAseel**
**Summary of change:**

- Previously, the deploy parser class returns undefined for any not found contract hash. Currently, the deploy parser returns a place holder of 'Not Available' for any undefined contract hash. 

**List of tasks:** 

- [x] Add place holder value.

**Steps for testing**
- Make sure your local git is up to date
```bash
git pull
```

- Checkout the branch `enhancement/deploy-parser-contract-hash`
```bash
git checkout enhancement/deploy-parser-contract-hash
```

- Run the test across the test-net
```bash
npm run test
```

- Confirm deploy-parser test has passed.
- Run example.

### CODE REVIEW

**Review by specialistvlad — APPROVED** [review]
LGTM

**Review by specialistvlad — APPROVED** [review]

**Review by jjfluid — APPROVED** [review]

**Review by jjfluid — COMMENTED** [review]
You know, it actually makes sense to have the transaction_index field here as well. Because the first time the deploys are requested from the blockchain is when you are iterating the hashes array from the block header. Might as well use the indices at that step, and then the transaction_index will already be known once we are at the defi event mapping stage.

**Comment by DevAseel** [comment]
> You know, it actually makes sense to have the transaction_index field here as well. Because the first time the deploys are requested from the blockchain is when you are iterating the hashes array from the block header. Might as well use the indices at that step, and then the transaction_index will already be known once we are at the defi event mapping stage.

Got it! Yes, I can include it as a parameter when parsing the deploy and then parse it with the deploy fields.

**Comment by DevAseel** [comment]
@jjfluid since this one is 92 commits behind this [PR](https://github.com/fluidefi/fluidefi-caspernet-aggregator-tools/pull/59), can I include the proposed changes in the last PR?

**Comment by jjfluid** [comment]
> @jjfluid since this one is 92 commits behind this [PR](https://github.com/fluidefi/fluidefi-caspernet-aggregator-tools/pull/59), can I include the proposed changes in the last PR?

Even though this will be used in the Deploys service, should be fine though. I will approve this though

**Review by jjfluid — APPROVED** [review]

**Comment by DevAseel** [comment]
> Even though this will be used in the Deploys service, should be fine though. I will approve this though

I actually had already implemented in event mapper service while I worked on the first event.

**Pull request merged**
